name: tuttorials
dependencies:
  - ipywidgets
  - jupyterlab
  - jupyterlab-lsp
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - python>=3.10
  - python-lsp-server
  - scipy
  - pip:
    - bokeh
    - hdbscan
    - panel
    - thisnotthat
    - umap
    - vectorizers
